import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { auth } from "@/auth";
import { SigninButton } from "@/auth/components";
import React from "react";
import { ProjectProvider } from "@/features/projects/contexts/ProjectProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const isSessionActive = !!session?.user;

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          {
            isSessionActive
              ? <>{children}</>
              : <SigninButton />
          }
        </Providers>
      </body>
    </html>
  );
}


function Providers({ children }: { children: React.ReactNode }) {
  return (
    <ProjectProvider>
      {children}
    </ProjectProvider>
  )
}
